/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BancoDeDados.Conexao;
import Controllers.CtrlCliente;
import Controllers.CtrlFornecedor;
import Controllers.CtrlOrdemServico;
import Controllers.CtrlProduto;
import Controllers.CtrlVeiculo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author deco
 */
public class JOrdemServico extends javax.swing.JFrame {
    private List listaVeiculo;
    private List listaCliente;
    private List listaProduto;
    private List listaProdutosOrdemServico;
    
    private int pecas_adicionadas = 0;
    
    private double preco_custo = 0;
    /**
     * Creates new form JOrdemServico
     */
    public JOrdemServico() {
        listaProdutosOrdemServico = new ArrayList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Label_CodCliente = new javax.swing.JLabel();
        Label_CodVeiculo = new javax.swing.JLabel();
        Label_Descricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descricao = new javax.swing.JTextArea();
        Label_Entrega = new javax.swing.JLabel();
        Label_Preco = new javax.swing.JLabel();
        PrecoCusto = new javax.swing.JFormattedTextField();
        Salvar = new javax.swing.JButton();
        BuscarCliente = new javax.swing.JButton();
        BuscarVeiculo = new javax.swing.JButton();
        Label_pecas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_Pecas = new javax.swing.JList();
        BuscarPeca = new javax.swing.JButton();
        Label_PrecoCusto = new javax.swing.JLabel();
        Label_PrecoServico = new javax.swing.JLabel();
        Label_desconto = new javax.swing.JLabel();
        PrecoDesconto1 = new javax.swing.JFormattedTextField();
        Label_PrecoTotal = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setResizable(false);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Titulo.setText("Nova ordem de serviço");

        Label_CodCliente.setText("Cliente:");

        Label_CodVeiculo.setText("Placa veículo:");

        Label_Descricao.setText("Descrição");

        Descricao.setColumns(20);
        Descricao.setRows(5);
        jScrollPane1.setViewportView(Descricao);

        Label_Entrega.setText("Entrega");

        Label_Preco.setText("Preços");

        PrecoCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$#,##0.##"))));
        PrecoCusto.setEnabled(false);

        Salvar.setText("Salvar");
        Salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        BuscarCliente.setText("Selecionar");
        BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteActionPerformed(evt);
            }
        });

        BuscarVeiculo.setText("Selecionar");
        BuscarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarVeiculoActionPerformed(evt);
            }
        });

        Label_pecas.setText("Peças");

        try
        {
            CtrlProduto ctrlProduto = new CtrlProduto();

            Connection con = (Connection) Conexao.getConnection();

            Statement stm = (Statement) con.createStatement();
        }
        catch (Exception e) { }

        // Code adding the component to the parent container - not shown here
        Lista_Pecas.setModel(new DefaultComboBoxModel(new Vector<String>(listaProdutosOrdemServico)));
        jScrollPane2.setViewportView(Lista_Pecas);

        BuscarPeca.setText("Adicionar Peça");
        BuscarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPecaActionPerformed(evt);
            }
        });

        Label_PrecoCusto.setText("Custo  (R$)");

        Label_PrecoServico.setText("Serviço (R$)");

        Label_desconto.setText("Desconto (%)");

        PrecoDesconto1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$#,##0.##"))));
        PrecoDesconto1.setEnabled(false);

        Label_PrecoTotal.setText("Total (R$)");

        try
        {
            CtrlCliente ctrl = new CtrlCliente();

            Connection con = (Connection) Conexao.getConnection();

            Statement stm = (Statement) con.createStatement();

            listaCliente = ctrl.carregaJListClienteFisico(stm);
            listaCliente.addAll(ctrl.carregaJListClienteJuridico(stm));
        }
        catch (Exception e) { }
        jComboBox1.setModel(new DefaultComboBoxModel(new Vector<String>(listaCliente)));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        try
        {
            CtrlVeiculo ctrl = new CtrlVeiculo();

            Connection con = (Connection) Conexao.getConnection();

            Statement stm = (Statement) con.createStatement();

            listaVeiculo = ctrl.carregaJListVeiculo(stm);
        }
        catch (Exception e) { }

        // Code adding the component to the parent container - not shown here
        jComboBox2.setModel(new DefaultComboBoxModel(new Vector<String>(listaVeiculo)));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try
        {
            CtrlProduto ctrlProduto = new CtrlProduto();

            Connection con = (Connection) Conexao.getConnection();

            Statement stm = (Statement) con.createStatement();

            listaProduto = ctrlProduto.carregaJListProduto(stm);
        }
        catch (Exception e) { }
        jComboBox3.setModel(new DefaultComboBoxModel(new Vector<String>(listaProduto)));

        jButton2.setText("Remover Peca");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("=");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setText("0.00");

        jTextField2.setText("0");

        try
        {
            MaskFormatter mascara = new MaskFormatter("##-##-####");
            mascara.setPlaceholderCharacter('_');

            jTextField3 = new JFormattedTextField(mascara);
        }
        catch(Exception e) {}

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Titulo)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Label_Entrega, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_Descricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_CodCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_CodVeiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Label_Preco)
                            .addComponent(Label_pecas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BuscarVeiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(BuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Label_PrecoCusto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PrecoCusto))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Label_PrecoServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Label_desconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PrecoDesconto1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Label_PrecoTotal))
                                        .addGap(32, 32, 32))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(0, 50, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BuscarPeca, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_CodCliente)
                    .addComponent(BuscarCliente)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_CodVeiculo)
                    .addComponent(BuscarVeiculo)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_pecas)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BuscarPeca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Descricao)
                        .addGap(30, 30, 30)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Entrega)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Label_Preco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_PrecoCusto)
                            .addComponent(Label_PrecoServico)
                            .addComponent(Label_desconto)
                            .addComponent(Label_PrecoTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrecoDesconto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Salvar)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteActionPerformed
        // TODO add your handling code here:
        try
        {
            CtrlVeiculo ctrl = new CtrlVeiculo();
            
            CtrlCliente cliente = new CtrlCliente();
        
            Connection con = (Connection) Conexao.getConnection();
        
            Statement stm = (Statement) con.createStatement();
        
            String nome = jComboBox1.getSelectedItem().toString();
            
            ResultSet rs = cliente.consultar(stm, nome);
            
            int idCliente = 0;
            
            while(rs.next())
            {
                idCliente = Integer.parseInt(rs.getString("idCliente"));
            }
            
            listaVeiculo = ctrl.carregaJListVeiculoPorCliente(stm, idCliente);
            jComboBox2.setModel(new DefaultComboBoxModel(new Vector<String>(listaVeiculo)));
        }
        catch (Exception e) { }
        
        BuscarCliente.setEnabled(false);
        jComboBox1.setEnabled(false);
    }//GEN-LAST:event_BuscarClienteActionPerformed

    private void BuscarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarVeiculoActionPerformed
        // TODO add your handling code here:
        try
        {
            CtrlVeiculo ctrl = new CtrlVeiculo();
            
            CtrlCliente cliente = new CtrlCliente();
        
            Connection con = (Connection) Conexao.getConnection();
        
            Statement stm = (Statement) con.createStatement();
        
            String placa = jComboBox2.getSelectedItem().toString();
            
            ResultSet rs = ctrl.consultar(stm, placa);
            
            int idCliente = 0;
            
            while(rs.next())
            {
                idCliente = Integer.parseInt(rs.getString("idCliente"));
            }
            
            listaCliente = cliente.carregaJListClienteAPartirDeVeiculo(stm, idCliente, placa);
            jComboBox1.setModel(new DefaultComboBoxModel(new Vector<String>(listaCliente)));
        }
        catch (Exception e) { }
        
        BuscarVeiculo.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_BuscarVeiculoActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void BuscarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPecaActionPerformed
        // TODO add your handling code here:
        int quantidade_produto = 0;
        
        try
        {
            CtrlProduto ctrlProduto = new CtrlProduto();
            
            CtrlFornecedor ctrlfornecedor = new CtrlFornecedor();
        
            Connection con = (Connection) Conexao.getConnection();
        
            Statement stm = (Statement) con.createStatement();
        
            String nome_produto = jComboBox3.getSelectedItem().toString();
            
            ResultSet rsProduto = ctrlProduto.consultarPorNome(stm, nome_produto);
            
            int idFornecedor = 0;
            
            int idProduto = 0;
            
            while(rsProduto.next())
            {
                idFornecedor = Integer.parseInt(rsProduto.getString("idFornecedor"));
                
                idProduto = Integer.parseInt(rsProduto.getString("idProduto"));
                
                quantidade_produto = Integer.parseInt(rsProduto.getString("quantidade"));
                
                preco_custo += Double.parseDouble(rsProduto.getString("valor_custo"));
            }
            PrecoCusto.setText("" + preco_custo);
        }
        catch (Exception e) { }
        
        if(quantidade_produto > 0)
        {
            listaProdutosOrdemServico.add(jComboBox3.getSelectedItem().toString());
        
            Lista_Pecas.setModel(new DefaultComboBoxModel(new Vector<String>(listaProdutosOrdemServico)));
        }
        else
            JOptionPane.showMessageDialog(this, "Peca Desejada não tem o suficiente");
        
        pecas_adicionadas++;
    }//GEN-LAST:event_BuscarPecaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            CtrlProduto ctrlProduto = new CtrlProduto();
            
            CtrlFornecedor ctrlfornecedor = new CtrlFornecedor();
        
            Connection con = (Connection) Conexao.getConnection();
        
            Statement stm = (Statement) con.createStatement();
        
            String nome_produto = (String)Lista_Pecas.getSelectedValue();
            
            ResultSet rsProduto = ctrlProduto.consultarPorNome(stm, nome_produto);
            
            int idFornecedor = 0;
            
            int idProduto = 0;
            
            while(rsProduto.next())
            {
                idFornecedor = Integer.parseInt(rsProduto.getString("idFornecedor"));
                
                idProduto = Integer.parseInt(rsProduto.getString("idProduto"));
                
                preco_custo -= Double.parseDouble(rsProduto.getString("valor_custo"));
            }
            PrecoCusto.setText("" + preco_custo);
        }
        catch (Exception e) { }
     
        listaProdutosOrdemServico.remove(Lista_Pecas.getSelectedIndex());
        
        Lista_Pecas.setModel(new DefaultComboBoxModel(new Vector<String>(listaProdutosOrdemServico)));
        
        pecas_adicionadas--;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        PrecoDesconto1.setText(""+(Double.parseDouble(PrecoCusto.getText()) + Double.parseDouble(jTextField1.getText()))*(1 - (Double.parseDouble(jTextField2.getText())) / 100));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        // TODO add your handling code here:
        if(BuscarCliente.isEnabled() == false && BuscarVeiculo.isEnabled() == false)
        {
            CtrlProduto ctrlProduto = new CtrlProduto();
            CtrlFornecedor ctrlfornecedor = new CtrlFornecedor();
            CtrlOrdemServico ctrlOrdemServico = new CtrlOrdemServico();
            CtrlVeiculo ctrlVeiculo = new CtrlVeiculo();
            CtrlCliente ctrlCliente = new CtrlCliente();

            for(int i = 0; i < pecas_adicionadas; i++)
            {
                try
                {
                    Connection con = (Connection) Conexao.getConnection();

                    Statement stm = (Statement) con.createStatement();

                    String nome_produto = Lista_Pecas.getModel().getElementAt(i).toString();

                    ResultSet rsProduto = ctrlProduto.consultarPorNome(stm, nome_produto);

                    int idFornecedor = 0;

                    int idProduto = 0;

                    while(rsProduto.next())
                    {
                        idFornecedor = Integer.parseInt(rsProduto.getString("idFornecedor"));

                        idProduto = Integer.parseInt(rsProduto.getString("idProduto"));

                        ctrlProduto.atualizaEstoque(stm, idProduto, idFornecedor);
                    }
                }
                catch (Exception e) { }
            }

            try
            {
                Connection con = (Connection) Conexao.getConnection();

                Statement stm = (Statement) con.createStatement();

                String placa = jComboBox2.getSelectedItem().toString();
            
                ResultSet rsVeiculo = ctrlVeiculo.consultar(stm, placa);

                int idCliente = 0;
                
                int idVeiculo = 0;
                
                
                while(rsVeiculo.next())
                {
                    idVeiculo = Integer.parseInt(rsVeiculo.getString("idVeiculo"));
                    
                    idCliente = Integer.parseInt(rsVeiculo.getString("idCliente"));
                }
                ctrlOrdemServico.adicionar(stm, Descricao.getText(), ctrlOrdemServico.converteData(jTextField3.getText()), idCliente, idVeiculo, placa);
            
                JOptionPane.showMessageDialog(this, "Ordem de Servico Efetuada!");
            }
            catch (Exception e) { }
            
            this.setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(this, "Operacão não realizada!\nNecessário selecionar Veículo e Cliente!");
    }//GEN-LAST:event_SalvarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JOrdemServico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarCliente;
    private javax.swing.JButton BuscarPeca;
    private javax.swing.JButton BuscarVeiculo;
    private javax.swing.JTextArea Descricao;
    private javax.swing.JLabel Label_CodCliente;
    private javax.swing.JLabel Label_CodVeiculo;
    private javax.swing.JLabel Label_Descricao;
    private javax.swing.JLabel Label_Entrega;
    private javax.swing.JLabel Label_Preco;
    private javax.swing.JLabel Label_PrecoCusto;
    private javax.swing.JLabel Label_PrecoServico;
    private javax.swing.JLabel Label_PrecoTotal;
    private javax.swing.JLabel Label_desconto;
    private javax.swing.JLabel Label_pecas;
    private javax.swing.JList Lista_Pecas;
    private javax.swing.JFormattedTextField PrecoCusto;
    private javax.swing.JFormattedTextField PrecoDesconto1;
    private javax.swing.JButton Salvar;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
